baseURL: https://elastic-benz-c73300.netlify.com/
title: Cyborg R&D
themesDir: "../"
theme: "hugo-theme-revealjs"

params:
    reveal_theme: black
    revealjs:
        controls: true
        progress: true
        history: true
        center: true
        height: 800
        width: 1500

disableKinds:
    - "sitemap"

outputs:
    home:
        - "html"
